# 390 bug-在线导入bad_alloc
**Environment:**
- OS: [cent os 7]
- CPU: 8 cores
- mem 32G
- TuGraph-DB Version [4.1.0]
- tugraph ha cluster with 3 nodes

造数据py脚本：
import json

test_dir = '/data/data/server/tugraph/tmp/'
total_count = 200000000


def write_entity():
    entity_dir = test_dir + "entity/"
    entity_file = open(entity_dir + "entity_0.txt", 'w')
    for seq in range(0, total_count):
        if seq % 10000000 == 0 and seq != 0:
            entity_file.close()
            file_name = entity_dir + "entity_" + str(seq / 10000000) + ".txt"
            entity_file = open(file_name, 'w')
        entity_file.write(str(seq))
        entity_file.write(chr(1))
        entity_file.write('mac')
        entity_file.write(chr(1))
        the_dict = {'name': 'name' + str(seq)}
        entity_file.write(json.dumps(the_dict))
        entity_file.write('\n')
    if not entity_file.closed:
        entity_file.close()


def write_one_relation(relation_file, seq_start: int, seq_end: int, relation_type: str):
    relation_file.write(str(seq_start))
    relation_file.write(chr(1))
    relation_file.write(str(seq_end))
    relation_file.write(chr(1))
    relation_file.write(relation_type)
    relation_file.write(chr(1))
    relation_file.write(relation_type + str(seq_start))
    relation_file.write(chr(1))
    the_dict = {'amount': 'amount' + str(seq_start)}
    relation_file.write(json.dumps(the_dict))
    relation_file.write('\n')


def write_relation():
    relation_dir = test_dir + "relation/"
    relation_file = open(relation_dir + "relation_0.txt", 'w')
    for seq in range(2, total_count):
        if seq % 10000000 == 0 and seq != 0:
            relation_file.close()
            file_name = relation_dir + "relation_" + str(seq / 10000000) + ".txt"
            relation_file = open(file_name, 'w')
        write_one_relation(relation_file, seq - 2, seq, 'transfer')
        write_one_relation(relation_file, seq - 1, seq, 'pay')
    if not relation_file.closed:
        relation_file.close()


if __name__ == "__main__":
    write_entity()
    write_relation()


------------------------
导入命令：
/data/data/server/tugraph/bin/lgraph_import -c /data/data/server/tugraph/tmp/test_online_import_config.config --delimiter "\001" --online true --full false  --graph yzjtest150m  --url http://10.101.1.105:7083/ --user admin --password 73@TuGraph --skip_packages 187

------------------
导入配置：
[root@yzdev01 /data/data/server/tugraph/tmp]$ cat /data/data/server/tugraph/tmp/test_online_import_config.config
{
  "files": [
    {
      "path": "/data/data/server/tugraph/tmp/entity/",
      "format": "CSV",
      "label": "entity",
      "columns": ["primary_key", "entity_type", "entity_properties"]
    },
    {
      "path": "/data/data/server/tugraph/tmp/relation/",
      "format": "CSV",
      "label": "relation",
      "SRC_ID": "entity",
      "DST_ID": "entity",
      "columns": ["SRC_ID", "DST_ID", "relation_type", "relation_unique_id", "relation_properties"]
    }
  ],
    "schema": [
    {
      "label": "entity",
      "primary":"primary_key",
      "type": "VERTEX",
      "properties": [
        { "name": "primary_key", "type": "STRING" },
        { "name": "entity_type", "type": "STRING" },
        { "name": "entity_properties", "type": "STRING","optional": true }
      ]
    },
    {
      "label": "relation",
      "type": "EDGE",
      "properties": [
        { "name": "relation_type", "type": "STRING", "optional": false },
        { "name": "relation_unique_id", "type": "STRING", "optional": false, "index":true,"unique":true },
        { "name": "relation_properties", "type": "STRING", "optional": true }
        ],
      "constraints": [["entity", "entity"]]
    }
  ]
}

执行导入命令后，导入日志报：
INFO  src/import/file_cutter.h:46] Finished reading file /data/data/server/tugraph/tmp/entity/entity_8.0.txt
[20240123 16:15:00.614228 0x00007f6ff82d5900 INFO  src/import/import_client.cpp:99] importing (188) packages
[20240123 16:15:10.830280 0x00007f6ff82d5900 INFO  toolkits/lgraph_import.cpp:295] An error occurred during import:
  status code error [status_code: 500, error_message: std::bad_alloc]


